# Generated by Django 4.2.13 on 2024-05-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='clock1.png', upload_to=''),
        ),
    ]
