# Generated by Django 4.2.13 on 2024-06-12 09:36

from django.db import migrations, models


def populate_product_info(apps, schema_editor):
    OrderItem = apps.get_model('store', 'OrderItem')
    for item in OrderItem.objects.all():
        if item.product:
            item.product_name = item.product.name
            item.product_price = item.product.price
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(blank=True,
                                      decimal_places=2,
                                      max_digits=10,
                                      null=True),
        ),
        migrations.RunPython(populate_product_info),
    ]
